CURRENCY_LINKS = {
    'GBP': 'R01035',
    'BYN': 'R01090',
    'AED': 'R01815',
    'USD': 'R01235',
    'EUR': 'R01239',
    'PLN': 'R01565',
    'BRL': 'R01115',
    'KRW': 'R01815',
    'KZT': 'R01335',
    'RSD': 'R01790B',
    'TRY': 'R01700J',
    'SEK': 'R01770',
    'CHF': 'R01775',
    'AZN': 'R01020',
    'GEL': 'R01300',
    'DKK': 'R01535',
    'INR': 'R01270',
    'KGS': 'R01370',
    'TJS': 'R01670',
    'JPY': 'R01820',
    'RON': 'R01705',
    'MDL': 'R01500',
    'THB': 'R01740',
    'AMD': 'R01060'
}

CURRENCY_NAMES = {
    'GBP': 'Фунт стерлингов',
    'BYN': 'Белорусский рубль',
    'AED': 'Дирхам ОАЭ',
    'USD': 'Доллар США',
    'EUR': 'Евро',
    'PLN': 'Польский злотый',
    'BRL': 'Бразильский реал',
    'KRW': 'Вон Республики Корея',
    'KZT': 'Казахстанский тенге',
    'RSD': 'Сербский динар',
    'TRY': 'Турецкая лира',
    'SEK': 'Шведская крона',
    'CHF': 'Швейцарский франк',
    'AZN': 'Азербайджанский манат',
    'GEL': 'Грузинский лари',
    'DKK': 'Датская крона',
    'INR': 'Индийская рупия',
    'KGS': 'Киргизский сом',
    'TJS': 'Таджикский сомони',
    'JPY': 'Японская иена',
    'RON': 'Румынский лей',
    'MDL': 'Молдавский лей',
    'THB': 'Таиландский бат',
    'AMD': 'Армянский драм'
}

SHARES_NAMES = {
    'YNDX': 'Яндекс',
    'SBER': 'Сбербанк',
    'TCSG': 'ТКС Холдинг',
    'GAZP': 'Газпром',
    'RNFT': 'Русснефть',
    'ROSN': 'Роснефть',
    'SNGSP': 'Сургутнефтегаз ап',
    'NVTK': 'НОВАТЭК',
    'AFKS': 'АФК Система',
    'FIVE': 'X5 Group',
    'MGNT': 'Магнит',
    'LKOH': 'ЛУКОЙЛ',
    'AFLT': 'Аэрофлот',
    'VTBR': 'ВТБ',
    'PLZL': 'Полюс',
    'MAGN': 'ММК'
}

MODELS_PATHS = {
    '../data/central_bank_rate.csv': '../models/cbr_model.json',
    '../data/inflation_rate.csv': '../models/inflr_model.json',
    '../data/currency/GBP_exchange_rate.csv': '../models/GBPr_model.json',
    '../data/currency/BYN_exchange_rate.csv': '../models/BYNr_model.json',
    '../data/currency/AED_exchange_rate.csv': '../models/AEDr_model.json',
    '../data/currency/USD_exchange_rate.csv': '../models/USDr_model.json',
    '../data/currency/EUR_exchange_rate.csv': '../models/EURr_model.json',
    '../data/currency/PLN_exchange_rate.csv': '../models/PLNr_model.json',
    '../data/currency/BRL_exchange_rate.csv': '../models/BRLr_model.json',
    '../data/currency/KRW_exchange_rate.csv': '../models/KRWr_model.json',
    '../data/currency/KZT_exchange_rate.csv': '../models/KZTr_model.json',
    '../data/currency/RSD_exchange_rate.csv': '../models/RSDr_model.json',
    '../data/currency/TRY_exchange_rate.csv': '../models/TRYr_model.json',
    '../data/currency/SEK_exchange_rate.csv': '../models/SEKr_model.json',
    '../data/currency/CHF_exchange_rate.csv': '../models/CHFr_model.json',
    '../data/currency/AZN_exchange_rate.csv': '../models/AZNr_model.json',
    '../data/currency/GEL_exchange_rate.csv': '../models/GELr_model.json',
    '../data/currency/DKK_exchange_rate.csv': '../models/DKKr_model.json',
    '../data/currency/INR_exchange_rate.csv': '../models/INRr_model.json',
    '../data/currency/KGS_exchange_rate.csv': '../models/KGSr_model.json',
    '../data/currency/TJS_exchange_rate.csv': '../models/TJSr_model.json',
    '../data/currency/JPY_exchange_rate.csv': '../models/JPYr_model.json',
    '../data/currency/RON_exchange_rate.csv': '../models/RONr_model.json',
    '../data/currency/MDL_exchange_rate.csv': '../models/MDLr_model.json',
    '../data/currency/THB_exchange_rate.csv': '../models/THBr_model.json',
    '../data/currency/AMD_exchange_rate.csv': '../models/AMDr_model.json',
    '../data/shares/YNDX_shares_rate.csv': '../models/YNDXr_model.json',
    '../data/shares/SBER_shares_rate.csv': '../models/SBERr_model.json',
    '../data/shares/TCSG_shares_rate.csv': '../models/TCSGr_model.json',
    '../data/shares/GAZP_shares_rate.csv': '../models/GAZPr_model.json',
    '../data/shares/RNFT_shares_rate.csv': '../models/RNFTr_model.json',
    '../data/shares/ROSN_shares_rate.csv': '../models/ROSNr_model.json',
    '../data/shares/SNGSP_shares_rate.csv': '../models/SNGSPr_model.json',
    '../data/shares/NVTK_shares_rate.csv': '../models/NVTKr_model.json',
    '../data/shares/AFKS_shares_rate.csv': '../models/AFKSr_model.json',
    '../data/shares/FIVE_shares_rate.csv': '../models/FIVEr_model.json',
    '../data/shares/MGNT_shares_rate.csv': '../models/MGNTr_model.json',
    '../data/shares/LKOH_shares_rate.csv': '../models/LKOHr_model.json',
    '../data/shares/AFLT_shares_rate.csv': '../models/AFLTr_model.json',
    '../data/shares/VTBR_shares_rate.csv': '../models/VTBRr_model.json',
    '../data/shares/PLZL_shares_rate.csv': '../models/PLZLr_model.json',
    '../data/shares/MAGN_shares_rate.csv': '../models/MAGNr_model.json'
}

PREDICTIONS_PATHS = {
    '../models/cbr_model.json': '../predictions/cbr_pred.csv',
    '../models/inflr_model.json': '../predictions/infl_pred.csv',
    '../models/GBPr_model.json': '../predictions/GBP_pred.csv',
    '../models/BYNr_model.json': '../predictions/BYN_pred.csv',
    '../models/AEDr_model.json': '../predictions/AED_pred.csv',
    '../models/USDr_model.json': '../predictions/USD_pred.csv',
    '../models/EURr_model.json': '../predictions/EUR_pred.csv',
    '../models/PLNr_model.json': '../predictions/PLN_pred.csv',
    '../models/BRLr_model.json': '../predictions/BRL_pred.csv',
    '../models/KRWr_model.json': '../predictions/KRW_pred.csv',
    '../models/KZTr_model.json': '../predictions/KZT_pred.csv',
    '../models/RSDr_model.json': '../predictions/RSD_pred.csv',
    '../models/TRYr_model.json': '../predictions/TRY_pred.csv',
    '../models/SEKr_model.json': '../predictions/SEK_pred.csv',
    '../models/CHFr_model.json': '../predictions/CHF_pred.csv',
    '../models/AZNr_model.json': '../predictions/AZN_pred.csv',
    '../models/GELr_model.json': '../predictions/GEL_pred.csv',
    '../models/DKKr_model.json': '../predictions/DKK_pred.csv',
    '../models/INRr_model.json': '../predictions/INR_pred.csv',
    '../models/KGSr_model.json': '../predictions/KGS_pred.csv',
    '../models/TJSr_model.json': '../predictions/TJS_pred.csv',
    '../models/JPYr_model.json': '../predictions/JPY_pred.csv',
    '../models/RONr_model.json': '../predictions/RON_pred.csv',
    '../models/MDLr_model.json': '../predictions/MDL_pred.csv',
    '../models/THBr_model.json': '../predictions/THB_pred.csv',
    '../models/AMDr_model.json': '../predictions/AMD_pred.csv',
    '../models/YNDXr_model.json': '../predictions/YNDX_pred.csv',
    '../models/SBERr_model.json': '../predictions/SBER_pred.csv',
    '../models/TCSGr_model.json': '../predictions/TCSG_pred.csv',
    '../models/GAZPr_model.json': '../predictions/GAZP_pred.csv',
    '../models/RNFTr_model.json': '../predictions/RNFT_pred.csv',
    '../models/ROSNr_model.json': '../predictions/ROSN_pred.csv',
    '../models/SNGSPr_model.json': '../predictions/SNGSP_pred.csv',
    '../models/NVTKr_model.json': '../predictions/NVTK_pred.csv',
    '../models/AFKSr_model.json': '../predictions/AFKS_pred.csv',
    '../models/FIVEr_model.json': '../predictions/FIVE_pred.csv',
    '../models/MGNTr_model.json': '../predictions/MGNT_pred.csv',
    '../models/LKOHr_model.json': '../predictions/LKOH_pred.csv',
    '../models/AFLTr_model.json': '../predictions/AFLT_pred.csv',
    '../models/VTBRr_model.json': '../predictions/VTBR_pred.csv',
    '../models/PLZLr_model.json': '../predictions/PLZL_pred.csv',
    '../models/MAGNr_model.json': '../predictions/MAGN_pred.csv'
}
